# Credenciais do banco de dados criados no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os comandos SQL que o Spring está fazendo por trás dos panos
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false